# Generated by Django 5.2 on 2025-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
