# Generated by Django 5.2 on 2025-05-30 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_user_venue_event_category_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='event_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.venue'),
        ),
        migrations.AddField(
            model_name='rating',
            name='event_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
